(define-module (cind core)
  #:use-module (cind host)
  #:export (install-default-keymaps!))

(define editor-bindings
  '(("C-x C-s" . "file.save")
    ("C-x C-w" . "file.save-as")
    ("C-x C-f" . "file.open")
    ("C-x p f" . "project.find-file")
    ("C-x p g" . "project.search")
    ("C-x b" . "buffer.switch")
    ("C-x k" . "buffer.kill")
    ("C-x Right" . "buffer.next")
    ("C-x Left" . "buffer.previous")
    ("C-x 2" . "window.split-below")
    ("C-x 3" . "window.split-right")
    ("C-x 0" . "window.delete")
    ("C-x 1" . "window.delete-others")
    ("C-x o" . "window.other")
    ("M-x" . "command.palette")
    ("C-g" . "keyboard.quit")
    ("C-s" . "search.prompt")
    ("C-r" . "search.backward-prompt")
    ("C-a" . "cursor.line-start")
    ("C-e" . "cursor.line-end")
    ("C-n" . "cursor.next-line")
    ("C-p" . "cursor.previous-line")
    ("C-f" . "cursor.forward-character")
    ("C-b" . "cursor.backward-character")
    ("C-v" . "cursor.page-down")
    ("M-v" . "cursor.page-up")
    ("C-/" . "edit.undo")
    ("C-_" . "edit.undo")
    ("C-x u" . "edit.undo")
    ("C-M-/" . "edit.redo")
    ("C-SPC" . "selection.toggle-mark")
    ("C-w" . "edit.kill-region")
    ("C-k" . "edit.kill-line")
    ("M-w" . "edit.copy-region")
    ("C-y" . "edit.yank")
    ("C-d" . "edit.delete-forward")
    ("C-l" . "editor.redraw")
    ("C-M-f" . "cursor.forward-expression")
    ("C-M-b" . "cursor.backward-expression")
    ("C-M-u" . "cursor.up-list")
    ("C-c e" . "selection.expand")
    ("C-c s" . "selection.contract")
    ("M-g g" . "cursor.goto-line")
    ("M-g n" . "location.next-error")
    ("M-g p" . "location.previous-error")
    ("C-x `" . "location.next-error")
    ("M-%" . "search.replace")
    ("C-h b" . "help.keys")
    ("C-x =" . "editor.position")
    ("RET" . "edit.newline")
    ("TAB" . "edit.indent")
    ("Backspace" . "edit.delete-backward")
    ("Delete" . "edit.delete-forward")
    ("C-u Backspace" . "edit.delete-backward-raw")
    ("C-u Delete" . "edit.delete-forward-raw")
    ("Left" . "cursor.backward-character")
    ("Right" . "cursor.forward-character")
    ("Up" . "cursor.previous-line")
    ("Down" . "cursor.next-line")
    ("PgUp" . "cursor.page-up")
    ("PgDn" . "cursor.page-down")
    ("Home" . "cursor.line-start")
    ("End" . "cursor.line-end")))

(define application-bindings
  '(("C-x C-c" . "application.quit")))

(define (bind-all! host keymap bindings)
  (let loop ((remaining bindings)
             (count 0))
    (if (null? remaining)
        count
        (let ((binding (car remaining)))
          (loop (cdr remaining)
                (if (bind-key-if-command! host
                                          keymap
                                          (car binding)
                                          (cdr binding))
                    (+ count 1)
                    count))))))

(define (install-default-keymaps! host)
  (+ (bind-all! host "editor.default" editor-bindings)
     (bind-all! host "application.global" application-bindings)))
